Repository shankarpandala/lazypredict, pull requests merged in 2020-07, with the labels that each got.

#103 Cardinality patch
  lazypredict/Supervised.py
Labels: enhancement

#104 gitignore-fix
  .vscode/settings.json
Labels: bug

#117 Added Installation section in README.rst, fixed typo, working on CONTRIBUTING. Closes #115
  CONTRIBUTING.rst
  README.rst
Labels: documentation

#118 Update README.rst - added print() function to both examples.
  README.rst
Labels: documentation
